[build]
  base = "apps/web"
  command = "npm install && npm run build"
  publish = "apps/web/build/client"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "apps/web/build/server"
  node_bundler = "esbuild"

